### ISSUE TITLE
CHG migrate docker images from buster to bullseye

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#205]
# Overview

[Debian Bullseye](https://www.debian.org/releases/bullseye/) was released yesterday (August 14th). We should migrate our images that are on buster to bullseye. This should be as simple as changing the tag on the docker images, rebuilding, and testing to make sure everything is still working right.

# TODO

- [ ] Change Dockerfiles to be `debian:bullseye` from `debian:buster`
- [ ] Build new imagess
- [ ] Test to make sure everything still works (most notably libmagic)
- [ ] Push & Re-deploy

**Comment by wabscale** [comment]
https://github.com/AnubisLMS/Anubis/commit/f5ddaf54e6009bbd65fc6d44e8442d76044a33bb
