### ISSUE TITLE
CHG UI REDESIGN

### ISSUE THREAD

**Issue by nysteo** [AnubisLMS/Anubis#243]
The following should be implemented in order for us to start moving to the new Anubis UI.

List of components to be implemented according to [Figma](https://www.figma.com/file/paYDaVKbPWVIYDnpTlUG0E/ANUBIS-UI?node-id=10%3A2058) design.
_NOTE: THIS LIST WILL BE CHANGING IN THE COMING WEEKS._

- [ ] CHG Update Theme To Support New Design ([#247](https://github.com/GusSand/Anubis/issues/247))
- [ ] CHG New Navbar Design ([#245](https://github.com/GusSand/Anubis/issues/245))
- [ ] CHG New Course Card Design ([#244](https://github.com/GusSand/Anubis/issues/244))
- [ ] CHG New Assignment Card Design ([#246](https://github.com/GusSand/Anubis/issues/246))
