### ISSUE TITLE
Winter Break & JTerm TODO

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#322]
# Overview

Many of the items that start here will likely get their own issues at a later date. The purpose of this issue is to start to plan the different features, project and changes that will go into Anubis over break. Feel free to comment whatever items you would like to propose.

## Higher Priority TODO

- [x] [Grading IDE](https://github.com/AnubisLMS/Anubis/issues/310)
- [ ] [ADD more test cases to improve test coverage](https://github.com/AnubisLMS/Anubis/issues/284)
- [ ] [Plagiarism Detection for Programming Assignments](https://github.com/AnubisLMS/Anubis/issues/274)
- [ ] [CHG modify submission pipelines to be able to handle grading all commits in a repo at once (bulk regrade optimization)](https://github.com/AnubisLMS/Anubis/issues/255)
- [ ] [ADD opt-in email notifications on events](https://github.com/AnubisLMS/Anubis/issues/126)
- [ ] Make logging a lot better using sidecar log exporters all over the place (web, api, ides, rpc, proxy....)

## Lower Priority TODO

- [ ] [ADD question button vs. Assign question button](https://github.com/AnubisLMS/Anubis/issues/320)
- [ ] [ADD a "Save all" button in the add question page](https://github.com/AnubisLMS/Anubis/issues/321)
- [x] [Frontend Logging Cleanup](https://github.com/AnubisLMS/Anubis/issues/319)
- [x] [ADD something to be able to disable a specific user](https://github.com/AnubisLMS/Anubis/issues/318)
- [x] [BUG Missing Create assignment repo button in the new frontned](https://github.com/AnubisLMS/Anubis/issues/317)
- [x] [ADD a button on the results page that shows the git difference](https://github.com/AnubisLMS/Anubis/issues/316)
- [x] [CHG convert the ide discord command to use an embed](https://github.com/AnubisLMS/Anubis/issues/315)
- [ ] [Upgrade new web to material 5](https://github.com/AnubisLMS/Anubis/issues/308)
- [x] New Profile Page
- [ ] Move to React-Query
- [ ] Apply Redesign to Admin Pages
- [ ] Build out theme with Typography & Button Variants
- [ ] Lazy Loading Components
- [x] [Python 3.10](https://github.com/AnubisLMS/Anubis/issues/267)
- [ ] [ADD check for broken assignment repo collaborator links to the reaper job](https://github.com/AnubisLMS/Anubis/issues/271)
- [x] [ADD Show diff between the expected output and the actual output in the autograder](https://github.com/AnubisLMS/Anubis/issues/254)
- [x] Convert existing Course IDEs to use new base image
- [x] Convert submission pipeline output to be more rich (make output json not just strings)
- [x] Rework Autograding tests structure
  - [x] Point values
  - [x] Hidden definition in tests
  - [x] Rethink current packaging
- [ ] Admin IDE changes
  - [ ] Sidecar docker daemon
- [x] IDE changes
  - [x] Maybe include the existing anubis cli? Integrate in autosave so its `anubis autosave`?
  - [x] zsh default shell
  - [x] oh-my-zsh things to make it look better
  - [x] Make provisioning individual student environments better

## Fever Dream Items

These are large ticket items that may be too big. Consider these proposals, not promises.

- [ ] Class Forums (like campuswire and piazza)

**Comment by wabscale** [comment]
@nysteo @GusSand  I'm sure you have your own list of items you would like to see. Let me know here

**Comment by AlpacaMax** [comment]
There's an idea I'm thinking about for the past few months. So currently every assignment has a built-in theia ide. I'm wondering if we can change it to be one type of a question. So it would be like those short respond questions, except when you click into it it's a coding question and students can click the `Anubis Cloud IDE` button to open an IDE for that specific question.

The benefit of doing that is in the future it's easier to introduce other types of questions, like questions that need to use a virtual machine or questions that need networking.

It's definitely going into Fever Dream Items. We need to refactor a lot of stuff for that to work.
